### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ErJokerITA** [qbcore-framework/qb-loading#10]
Impossible to Changing branding!
I've changed with another .svg (same name and dimensions) but not load !

**Comment by 12Echo** [comment]
i just removed the branding, found it simpler than making a .svg

**Comment by 12Echo** [comment]
> Impossible to Changing branding! I've changed with another .svg (same name and dimensions) but not load !

ok so I was going through it & found on line 186 you can put /assests/branding/(your file name here) to whatever you named the .svg file kinda like this:  http://ss.jimmyfalcone.com/exmshdx7.png

**Comment by ErJokerITA** [comment]
I don't understand why but no works ... i thinks is better to puto logo manually on images ... so i can place better...
