### ISSUE TITLE
Video option doesnt work even with default video. 

### ISSUE THREAD

**Issue by kingofkingzcd** [qbcore-framework/qb-loading#13]
No errors. Video option doesnt work. tried it with default videos and custom videos. made sure i enabled video in index and disabled the photos as well.

**Comment by GoodLoongStudio** [comment]
Me neither. I tried many video clips , Only a 3 seconds video works

**Comment by ZumieFiasco** [comment]
Downloaded and Tested 7/2/22 4pm Central US 

Custom Video works for me but only plays for a few seconds and then freezes around 30% load consistently and then remains frozen until server is fully loaded. 

- I have confirmed proper format of my custom video to be mp4/h264 just like the default video that comes with the script. 

- Not sure if file size or duration of video plays into as a factor in this but in its current state it is a consistent issue and not working for me. 

- I have tested one custom video in mp4 format and an ncs music video downloaded from youtube in mp4 format and the issue persists.

**Comment by GoodLoongStudio** [comment]
I found a way to paly Custom Video. The Data rate should not too high, and the Frame rate should be 30FPS, Just FYI 
![image](https://user-images.githubusercontent.com/24458200/177023576-dda063ea-dbdb-4625-bb0c-ddcb8706745f.png)

There is another issue. My video doesn't display FULLSCREEN，as my monitor is 2k resolution

![image](https://user-images.githubusercontent.com/24458200/177024078-ba49af24-2228-43f2-be01-fe33127bc4c9.png)

**Comment by DOSEOFiNSANiTY** [comment]
Same issue here... The discord support is practically useless and no one really responds to anything support wise when its something like this. So maybe commenting here will get the point to stick a tad better.

Lots of people are reporting the same issue. Vue.js is most likely the issue, but I am still trying to diagnose and come up with a solution since there seems to be a lot of radio silence. 

As for the 2K quality. Change the height values inside the HTML file. Also make sure the metadata of the file reflects those values. If the resolution of the video is only 1080p, you will need to upscale it or find an alternative file to use.

**Comment by TrevrSomething** [comment]
Change your fxmanifest, should fix the black screen.

fx_version 'adamant'

**Comment by KazukiDev** [comment]
when i add a video it show a white screen

**Comment by 3S-Digital-Agency** [comment]
> Change your fxmanifest, should fix the black screen.
> 
> fx_version 'adamant'

it ain't fixed the blackscreen, do you got an other idea?

**Comment by TeamFishbowl** [comment]
Honestly i am lost. i have tried rendering videos in every way, in vegas and in after effects. no matter the bitrate, frame rate or resolution, all of them black screen...the original video it comes with is the ONLY video that works..... Changing the fxmanifest did not help.

**Comment by KazukiDev** [comment]
How do i fix this white screen
![image](https://github.com/qbcore-framework/qb-loading/assets/75772083/9c07cbf4-34e8-406e-bf4d-31c844e0c6d3)

**Comment by SpaceFoon** [comment]
Ok I just tried a lot of stuff to get this to work. The trick for me was to have a really small in size video like 1.5 megs or just web optimize your video. That worked with a 26 meg 30 second video at 60fps 192kbps audio. I think its trying to play the video before being loaded and just giving up. With web optimization it will be able to play even before fully loaded.

**Comment by SpaceFoon** [comment]
This is solved by using web optimized video.
