### ISSUE TITLE
inifity loadingscreen

### ISSUE THREAD

**Issue by RoYaL69** [qbcore-framework/qb-loading#19]
i got the default settings and newest versions of all resources. i tried loadscreen_manual_shutdown 'yes' and 'no' but no changes. if i disable this resource i can join the server, all works fine. i noticed that at the end of the loading on the top left there is a red scare blinking shortly, after that nothing happend anymore and iam stuck in an infinity loading loop. i got all qb resources installed and they work all properly.

**Comment by dbryant912** [comment]
I have exactly the same issue, as soon as I remove qb-loading the server works

**Comment by ReNsTeR501** [comment]
same. /bump

**Comment by bgtracker** [comment]
Same ./bump

**Comment by bgtracker** [comment]
@GhzGarage
