### ISSUE TITLE
How to create bind images?

### ISSUE THREAD

**Issue by OLIX-boop** [qbcore-framework/qb-loading#2]
Hi, how can I create bind images like in assets/keybinds ??

**Comment by MonkeyWhisper** [comment]
Ask in QBCore for support or LJ Labs.

**Comment by OLIX-boop** [comment]
> Ask in QBCore for support or LJ Labs.

Do you have the LJ labs discord link?

**Comment by ItsANoBrainer** [comment]
https://discord.gg/ljlabs
