### ISSUE TITLE
[bug] Video not scaling to screen size

### ISSUE THREAD

**Issue by SirOMGitsYOU** [qbcore-framework/qb-loading#4]
Hey!

Would love to use this with the MP4 video on my server however it looks like the video is hard coded to 1080p and  I can seem to work out a fix for it - https://i.imgur.com/BqRWXpK.png

**Comment by ItsANoBrainer** [comment]
Dynamic scaling would be best I agree.

**Comment by MCDesignDK** [comment]
Any updates on this issue?

**Comment by loljoshie** [comment]
Unfortunately, this isn't necessarily a bug. Currently it's meant for 1080p resolutions. This is more so an improvement request you'd like to see added in the future. I'll keep it in mind! Thanks!
